Feature/12517 fss UI simplified search add download all button
UKHO/file-share-service-ui pull request #101
Opened 2022-03-01 14:43 UTC by mohamme15315

Added download all button on simplified search result with unit testing

2022-03-01 15:59 UTC, crdandoukho requested changes
In addition to my comments, please also fix the failing unit test:
`FssSearchResultsComponent › should return search result count 1 when search result for 1 batch is provided` in (fss-search-results.component.spec.ts)

At the time of writing I have not been able to run the functional tests because the DevOps pipeline is running very slowly

2022-03-01 15:59 UTC, crdandoukho commented on Tests/UnitTests/fss-search-results.component.spec.ts
> +        if (item.allFilesZipSize != undefined && item.allFilesZipSize != null) {
Please change this to a simple 'truthy' condition
```suggestion
        if (item.allFilesZipSize) {
```
If `allFilesZipSize` is zero we don't want to display the download button

2022-03-01 15:59 UTC, crdandoukho commented on Tests/UnitTests/fss-search-results.component.spec.ts
> +        if (item.allFilesZipSize != undefined && item.allFilesZipSize != null) {
Please add an inverse assertion to prove the button is present when `allFileZipSize` is truthy

2022-03-01 15:59 UTC, crdandoukho commented on src/app/features/fss-search/fss-search-results/fss-search-results.component.html
> +      <ng-container *ngIf="batch.allFilesZipSize!=null">
Please change this to a simple 'truthy' condition
```suggestion
      <ng-container *ngIf="batch.allFilesZipSize">
```
Doing this covers undefined and zero

2022-03-01 15:59 UTC, crdandoukho commented on src/app/features/fss-search/fss-search-results/fss-search-results.component.ts
> +          allFilesZipSize:batches[i]["allFilesZipSize"]
Please use single quote delimiter
```suggestion
          allFilesZipSize:batches[i]['allFilesZipSize']
```

2022-03-02 14:27 UTC, crdandoukho requested changes
Please extend the new test to prove the [Download all] button is _not_ displayed when `allFilesZipSize` is falsy

2022-03-02 14:27 UTC, crdandoukho commented on Tests/UnitTests/fss-search-results.component.spec.ts
> +        }
Please extend this test to prove the [Download all] button is _not_ displayed when `allFilesZipSize` is falsy

For example
```suggestion
        } else {
         assert here that [Download all] button is not displayed
        }
```

2022-03-04 13:06 UTC, bhalcha13813 approved these changes
LGTM

2022-03-04 16:04 UTC, merged