Feature/13616 fss UI automation test framework upgrade playwright jest to playwright test runner
UKHO/file-share-service-ui pull request #140
Opened 2022-07-21 07:23 UTC by kishorambare

Hi All,

This PR is consist of suggested changes and recommendations for changing existing playwright jest to Playwright Test Runner.

Kindly review it and approve.
Thanks.

2022-07-21 16:42 UTC, crdandoukho requested changes
I get the following error when trying to build locally:

$> npm ci
npm ERR! bindings not accessible from watchpack-chokidar2:fsevents

Could you please fix

2022-07-26 15:11 UTC, crdandoukho requested changes
Please investigate why the FileTransform step of the Functional Test job is failing in the pipeline

2022-07-29 12:42 UTC, RaviK2233 approved these changes

2022-08-03 07:56 UTC, crdandoukho approved these changes
Looks good

2022-08-03 07:56 UTC, merged