Feature/13837 UI automation sprint2 pb is
UKHO/file-share-service-ui pull request #153
Opened 2022-08-19 07:11 UTC by kishorambare

HI All,

This PR is consist of UI Automation of Sprint 2 PBI's.

Kindly review and approve.
Thanks.

2022-08-19 11:28 UTC, RaviK2233 requested changes
- Can we please move TestData folder from root to Test folder 
- Replace test 13809, 13815 with the test that confirms that all cells are uploaded 
- Test case 13811 & 13811 is for valid and invalid ENC but the test is not validating invalid/duplicated ENC
- Test Case 13823/13826 validates if error message is displayed for duplicated ENC but does not assert if duplicated ENC is not loaded in Grid

2022-08-22 05:33 UTC, kishorambare commented
> 



> * Can we please move TestData folder from root to Test folder
> * Replace test 13809, 13815 with the test that confirms that all cells are uploaded
> * Test case 13811 & 13811 is for valid and invalid ENC but the test is not validating invalid/duplicated ENC
> * Test Case 13823/13826 validates if error message is displayed for duplicated ENC but does not assert if duplicated ENC is not loaded in Grid

Hi @RaviK2233,
Resolved review comments. Pls have a look and approve.
For point number 3, as discussed earlier those are large files, so just verified the error message.
Also the similar tests has been covered in point 4

2022-08-23 07:56 UTC, RaviK2233 approved these changes

2022-08-23 08:59 UTC, crdandoukho approved these changes
Looks good

2022-08-23 09:10 UTC, merged