Feature/13029 ess u i show exchange set progress screen and guestimated size
UKHO/file-share-service-ui pull request #162
Opened 2022-09-01 15:17 UTC by Rajesh14881

Added Estimated Size with Spinner

2022-09-02 12:38 UTC, rvijayavel approved these changes
Looks good.

2022-09-05 08:18 UTC, crdandoukho requested changes
Please resolve merge conflicts

2022-09-05 13:39 UTC, crdandoukho requested changes
Only a very small change needed please

2022-09-05 13:39 UTC, crdandoukho commented on Tests/UnitTests/ess-download-exchangeset.component.spec.ts
> +      avgSizeofENC: 0.3
Please change to `avgSizeofENCinMB`
```suggestion
      avgSizeofENCinMB: 0.3
```

2022-09-05 13:52 UTC, merged