Feature/13030 poll fss for batch status
UKHO/file-share-service-ui pull request #168
Opened 2022-09-08 07:25 UTC by chaital14503

Code changes for removing spinner after batch status is "Committed", and download button implementation. 
Kindly review the changes.

2022-09-08 10:33 UTC, crdandoukho requested changes

2022-09-09 08:07 UTC, chaital14503 commented on src/app/features/exchange-set/ess-download-exchangeset/ess-download-exchangeset.component.ts
> +      if (response.status == "Committed") {
Added another condition for batchstatus Incomplete or CommitInProgress, and else part for Rolledback and Failed. UTs updated accordingly. Thanks.

2022-09-09 09:46 UTC, crdandoukho approved these changes
Looks good

2022-09-09 11:34 UTC, rvijayavel approved these changes
Looks good.

2022-09-09 14:56 UTC, crdandoukho approved these changes
Looks good

2022-09-09 14:57 UTC, merged