10372 automated accessibility test using axe playwright
UKHO/file-share-service-ui pull request #25
Opened 2021-07-22 18:59 UTC by kajalkundu

This pull request for automated accessibility tests using axe playwright and jest framework.

2021-07-26 10:02 UTC, gregzealley requested changes

2021-07-26 10:02 UTC, gregzealley commented on package.json
>      "@types/jest-axe": "^3.5.1",
Can jest-axe be removed?

2021-07-26 10:02 UTC, gregzealley commented on Tests/FunctionalTests/fss-home.spec.ts
> +    jest.setTimeout(30000);
Worth having this value as a constant?

2021-07-27 07:19 UTC, gregzealley approved these changes

2021-07-28 09:47 UTC, gregzealley approved these changes

2021-07-29 10:30 UTC, bhalcha13813 approved these changes
Looks good to me

2021-08-06 15:19 UTC, martyn-fewtrell approved these changes
Looks good

2021-08-16 09:23 UTC, martyn-fewtrell approved these changes
Looks good

2021-08-16 09:23 UTC, merged