12546-FSS-UI Refresh Batch Attributes Stored In Local Storage On Token Refresh Changes
UKHO/file-share-service-ui pull request #77
Opened 2022-01-18 10:44 UTC by gaurav15233

Hi All, Please review and merge changes related to the refresh batch attributes stored in local storage on token refresh changes for FSS UI in main branch.

2022-01-18 14:22 UTC, jimjamjahaa requested changes
just 2 small changes required

2022-01-18 15:09 UTC, bhalcha13813 approved these changes
LGTM

2022-01-19 04:18 UTC, gaurav15233 commented
Hi Richard, Thanks for reviewing PR. I have done the changes as per comments. Can you please review this.

2022-01-19 11:22 UTC, jimjamjahaa approved these changes
lgtm

2022-01-19 11:51 UTC, crdandoukho reviewed
Just one question re the duplicated event subscription

2022-01-19 11:51 UTC, crdandoukho commented on src/app/features/fss-search/fss-search.component.ts
> +      this.fileShareApiService.getBatchAttributes().subscribe((batchAttributeResult) => {
Can the code in the new subscription for the `getBatchAttributes` event be performed in the existing event handler  on line 82?

2022-01-19 15:35 UTC, crdandoukho commented on src/app/features/fss-search/fss-search.component.ts
> +      this.fileShareApiService.getBatchAttributes().subscribe((batchAttributeResult) => {
Forget that. After debugging I see I have misunderstood how `subscribe()` is working and the callback on line 82 is not called after the log-in pop up

2022-01-19 15:49 UTC, crdandoukho commented
@gaurav15233 could you please resolve the merge conflicts?

2022-01-20 08:49 UTC, gaurav15233 commented
Hi Chris, Thanks for reviewing this PR. I have resolved the merge conflicts. Can you please review again.

2022-01-20 10:03 UTC, merged