Feature/12527 fss UI connect search filter panel with get batch attributes endpoint
UKHO/file-share-service-ui pull request #92
Opened 2022-02-15 11:32 UTC by gaurav15233

Hi All, Please review and merge changes related to connect search filter panel with get batch attributes endpoint for FSS UI in main branch.

2022-02-15 15:55 UTC, jimjamjahaa reviewed
lgtm but the tests are failing atm

2022-02-16 14:01 UTC, jimjamjahaa requested changes
i appologise for not picking these things up first time round but there are some things to look at

this PR seems to have similar code to PR 91 so i hope 2 people aren't trying to fix the same thing :)

2022-02-16 14:01 UTC, jimjamjahaa commented on src/app/features/fss-search/fss-search.component.ts
> +    for (var i = 0; i < batch.length; i++) {
another var that should be let

2022-02-16 14:31 UTC, gaurav15233 commented on Tests/UnitTests/fss-search.component.spec.ts
> +    var inputSearchResultData = <JSON>inputSearchResultMockData;
updated as suggested. Thanks

2022-02-16 14:35 UTC, gaurav15233 commented on Tests/UnitTests/fss-search.component.spec.ts
> +export var inputSearchResultMockData: any =
updated as suggested. Thanks

2022-02-16 14:35 UTC, gaurav15233 commented on src/app/core/services/file-share-api.service.ts
> +                return this.http.get(this.baseUrl + "/attributes/search?$filter=" + encodeURIComponent(payload));
updated as suggested. Thanks

2022-02-16 14:37 UTC, gaurav15233 commented on src/app/features/fss-search/fss-search.component.ts
> +      for (var i = 0; i < batchAttributesResult.length; i++) {
Similar comments we resolved in PR 91

2022-02-16 14:38 UTC, gaurav15233 commented on src/app/features/fss-search/fss-search.component.ts
> +    for (var i = 0; i < batch.length; i++) {
updated as suggested. Thanks

2022-02-16 16:28 UTC, bhalcha13813 approved these changes
LGTM

2022-02-17 11:51 UTC, jimjamjahaa reviewed
LGTM but there are merge conflicts

2022-02-17 15:19 UTC, gaurav15233 commented
Hi Richard, I have resolved the merge conflicts.
Thank you.

2022-02-18 10:09 UTC, merged